artifacts_root: artifacts


# data loading configuration
data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_file_path: data/train.csv
  val_data_file_path: data/validation.csv
  test_data_file_path: data/test.csv
  status_file: artifacts/data_ingestion/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_file_path: data/train.csv
  val_data_file_path: data/validation.csv
  test_data_file_path: data/test.csv

